services:
  dummy_smartgen:
    build:
      context: ./dummy-smartgen
      dockerfile: Dockerfile
    container_name: dummy-smartgen
    restart: unless-stopped
    volumes:
      - ./dummy-smartgen/logs:/app/logs
    networks:
      - wbor-network
    profiles:
      - development

  rabbitmq:
    image: rabbitmq:3.11-management
    container_name: rabbitmq
    restart: unless-stopped
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"   # AMQP port
      - "15672:15672" # Management UI
    networks:
      - wbor-network
    profiles:
      - development

networks:
  wbor-network:
    external: true