services:
  encoder:
    build:
      context: ./encoder
      dockerfile: Dockerfile
    container_name: wbor-rds-encoder
    restart: always
    env_file:
      - ./encoder/.env
    volumes:
      - ./encoder/logs:/app/logs
    networks:
      - wbor-network

networks:
  wbor-network:
    external: true
    # Custom network for inter-container communication